CREATE DATABASE Exercise5;

CREATE TABLE KHACHHANG (
	MAKH Nvarchar (5),
	TENKH Nvarchar (30),
	DIACHI Nvarchar (50),
	DT Nvarchar (10),
	EMAIL Nvarchar (30),
	PRIMARY KEY (MAKH)
);

ALTER TABLE KHACHHANG
ALTER COLUMN TENKH Nvarchar(10) NOT NULL;


CREATE TABLE VATTU (
	MAVT Nvarchar (5),
	TENVT Nvarchar (30),
	DVT Nvarchar (20),
	GIAMUA int,
	SLTON int,
	PRIMARY KEY (MAVT)
);

ALTER TABLE VATTU
ALTER COLUMN TENVT Nvarchar(30) NOT NULL;

ALTER TABLE VATTU
ADD CHECK (GIAMUA > 0);

ALTER TABLE VATTU
ADD CHECK (SLTON > 0);

CREATE TABLE HOADON (
	 MAHD Nvarchar (10),
	 NGAY DateTime,
	 MAKH Nvarchar (5),
	 TONGTG int,
	 PRIMARY KEY (MAHD)
);

ALTER TABLE HOADON 
ADD FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH);	

CREATE TABLE CHITIETHOADON (
	MAHD Nvarchar (10),
	MAVT Nvarchar (5),
	SL int,
	KHUYENMAI int,
	GIABAN int,
	PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE CHITIETHOADON 
ADD FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD);

ALTER TABLE CHITIETHOADON 
ADD FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);
