-- exercise 10
-- 1. Trường GiaMua trong bảng VATTU
CREATE NONCLUSTERED INDEX idx_GIAMUA ON VATTU(GIAMUA);
-- 2. Trường SLTon trong bảng VATTU
CREATE NONCLUSTERED INDEX idx_SLTON ON VATTU(SLTON);
-- 3. Trường Ngay trong bảng HOADON.
CREATE NONCLUSTERED INDEX idx_NGAY ON HOADON(NGAY);